// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupOriginalFiles(arg1) {
  return window['go']['main']['App']['BackupOriginalFiles'](arg1);
}

export function BrowseExe() {
  return window['go']['main']['App']['BrowseExe']();
}

export function DetectGames() {
  return window['go']['main']['App']['DetectGames']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetGameDetails(arg1) {
  return window['go']['main']['App']['GetGameDetails'](arg1);
}

export function GetGameFolderPreview(arg1) {
  return window['go']['main']['App']['GetGameFolderPreview'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDLSS5(arg1) {
  return window['go']['main']['App']['InstallDLSS5'](arg1);
}

export function InstallReshade(arg1) {
  return window['go']['main']['App']['InstallReshade'](arg1);
}

export function KillGameProcess(arg1) {
  return window['go']['main']['App']['KillGameProcess'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function PatchGame(arg1) {
  return window['go']['main']['App']['PatchGame'](arg1);
}

export function UninstallPatch(arg1) {
  return window['go']['main']['App']['UninstallPatch'](arg1);
}
