// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDefenderExclusion(arg1:string):Promise<main.PatchResult>;

export function BackupOriginalFiles(arg1:string):Promise<main.PatchResult>;

export function BrowseExe():Promise<string>;

export function DetectGames():Promise<Array<main.GameInfo>>;

export function GetAppVersion():Promise<string>;

export function GetDefenderStatus():Promise<main.DefenderStatus>;

export function GetDownloadURLs():Promise<main.DownloadURLs>;

export function GetGPUs():Promise<Array<main.GpuInfo>>;

export function GetGameDetails(arg1:string):Promise<main.GameDetails>;

export function GetGameDetailsForExe(arg1:string,arg2:string):Promise<main.GameDetails>;

export function GetGameFolderPreview(arg1:string):Promise<main.GameInfo>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function InstallDLSS5(arg1:string):Promise<main.PatchResult>;

export function InstallDgVoodoo(arg1:string):Promise<main.PatchResult>;

export function InstallFeeder32(arg1:string):Promise<main.PatchResult>;

export function InstallOptiScaler(arg1:string):Promise<main.PatchResult>;

export function InstallReshade(arg1:string):Promise<main.PatchResult>;

export function IsPathExcluded(arg1:string):Promise<boolean>;

export function KillGameProcess(arg1:string):Promise<string>;

export function LaunchGame(arg1:string):Promise<main.PatchResult>;

export function ListGameExes(arg1:string):Promise<Array<main.GameExeInfo>>;

export function OpenGameFolder(arg1:string):Promise<main.PatchResult>;

export function PatchGame(arg1:string):Promise<main.PatchResult>;

export function PatchGameWithMode(arg1:string,arg2:string):Promise<main.PatchResult>;

export function PatchGameWithModeForExe(arg1:string,arg2:string,arg3:string):Promise<main.PatchResult>;

export function RefreshGPUs():Promise<Array<main.GpuInfo>>;

export function RemoveDefenderExclusion(arg1:string):Promise<main.PatchResult>;

export function RepairInstall(arg1:string):Promise<main.VerifyReport>;

export function RepairInstallForExe(arg1:string,arg2:string):Promise<main.VerifyReport>;

export function SaveDownloadURLs(arg1:main.DownloadURLs):Promise<main.PatchResult>;

export function SelectGPU(arg1:string):Promise<main.GpuInfo>;

export function UninstallPatch(arg1:string):Promise<main.PatchResult>;

export function VerifyInstall(arg1:string):Promise<main.VerifyReport>;

export function VerifyInstallForExe(arg1:string,arg2:string):Promise<main.VerifyReport>;
