// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDefenderExclusion(arg1) {
  return window['go']['main']['App']['AddDefenderExclusion'](arg1);
}

export function BackupOriginalFiles(arg1) {
  return window['go']['main']['App']['BackupOriginalFiles'](arg1);
}

export function BrowseExe() {
  return window['go']['main']['App']['BrowseExe']();
}

export function DetectGames() {
  return window['go']['main']['App']['DetectGames']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDefenderStatus() {
  return window['go']['main']['App']['GetDefenderStatus']();
}

export function GetDownloadURLs() {
  return window['go']['main']['App']['GetDownloadURLs']();
}

export function GetGPUs() {
  return window['go']['main']['App']['GetGPUs']();
}

export function GetGameDetails(arg1) {
  return window['go']['main']['App']['GetGameDetails'](arg1);
}

export function GetGameDetailsForExe(arg1, arg2) {
  return window['go']['main']['App']['GetGameDetailsForExe'](arg1, arg2);
}

export function GetGameFolderPreview(arg1) {
  return window['go']['main']['App']['GetGameFolderPreview'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallDLSS5(arg1) {
  return window['go']['main']['App']['InstallDLSS5'](arg1);
}

export function InstallDgVoodoo(arg1) {
  return window['go']['main']['App']['InstallDgVoodoo'](arg1);
}

export function InstallFeeder32(arg1) {
  return window['go']['main']['App']['InstallFeeder32'](arg1);
}

export function InstallOptiScaler(arg1) {
  return window['go']['main']['App']['InstallOptiScaler'](arg1);
}

export function InstallReshade(arg1) {
  return window['go']['main']['App']['InstallReshade'](arg1);
}

export function IsPathExcluded(arg1) {
  return window['go']['main']['App']['IsPathExcluded'](arg1);
}

export function KillGameProcess(arg1) {
  return window['go']['main']['App']['KillGameProcess'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function ListGameExes(arg1) {
  return window['go']['main']['App']['ListGameExes'](arg1);
}

export function OpenGameFolder(arg1) {
  return window['go']['main']['App']['OpenGameFolder'](arg1);
}

export function PatchGame(arg1) {
  return window['go']['main']['App']['PatchGame'](arg1);
}

export function PatchGameWithMode(arg1, arg2) {
  return window['go']['main']['App']['PatchGameWithMode'](arg1, arg2);
}

export function PatchGameWithModeForExe(arg1, arg2, arg3) {
  return window['go']['main']['App']['PatchGameWithModeForExe'](arg1, arg2, arg3);
}

export function RefreshGPUs() {
  return window['go']['main']['App']['RefreshGPUs']();
}

export function RemoveDefenderExclusion(arg1) {
  return window['go']['main']['App']['RemoveDefenderExclusion'](arg1);
}

export function RepairInstall(arg1) {
  return window['go']['main']['App']['RepairInstall'](arg1);
}

export function RepairInstallForExe(arg1, arg2) {
  return window['go']['main']['App']['RepairInstallForExe'](arg1, arg2);
}

export function SaveDownloadURLs(arg1) {
  return window['go']['main']['App']['SaveDownloadURLs'](arg1);
}

export function SelectGPU(arg1) {
  return window['go']['main']['App']['SelectGPU'](arg1);
}

export function UninstallPatch(arg1) {
  return window['go']['main']['App']['UninstallPatch'](arg1);
}

export function VerifyInstall(arg1) {
  return window['go']['main']['App']['VerifyInstall'](arg1);
}

export function VerifyInstallForExe(arg1, arg2) {
  return window['go']['main']['App']['VerifyInstallForExe'](arg1, arg2);
}
